### PR TITLE
Feature: add parameter exclude_from_purge

### PR DESCRIPTION
**Pull request by ricardozv28**
# Summary of PR changes
- Add parameter to allow pass comma separate list for folders/files to keep during the deployment cleaning

## PR Requirements
- [x] For major, minor, or breaking changes, at least one of the commit messages contains the appropriate `+semver:` keywords.
  - See the *Incrementing the Version* section of the repository's README.md for more details.
- [x] The action code does not contain sensitive information.

*NOTE: If the repo's workflow could not automatically update the `README.md`, it should be updated manually with the next version.  For javascript actions, if the repo's workflow could not automatically recompile the action it should also be updated manually as part of the PR.*

### CODE REVIEW

**Review by hpractv — DISMISSED** [review]
👍🏽   Please make sure to update the workflow templates that use this action: https://github.com/im-practices/.github/tree/main/workflow-templates

**Comment by ricardozv28** [comment]
> 👍🏽 Please make sure to update the workflow templates that use this action: https://github.com/im-practices/.github/tree/main/workflow-templates

here is the PR for the workflow template updates

https://github.com/im-practices/.github/pull/217

**Comment by chris-tineo** [comment]
Hello. Can we merge this PR? It will be really helpful for me because it's just the feature that I need to migrate one of my applications from Octopus to Github Actions.

**Review by hpractv — APPROVED** [review]
👍🏽

**Comment by ricardozv28** [comment]
Seems like the required action is failing cause my PR was made from a forked repo, maybe is there a way of bypass it and merge it?

**Pull request merged**
